ALTER DATABASE CURRENT SET SINGLE_USER WITH ROLLBACK IMMEDIATE
ALTER DATABASE CURRENT COLLATE Hungarian_CI_AS
ALTER TABLE fajok ALTER COLUMN nev VARCHAR(50) COLLATE Hungarian_CI_AS
ALTER DATABASE CURRENT SET MULTI_USER WITH ROLLBACK IMMEDIATE